src/Entity/Wish.php
<?php

namespace App\Entity;

use App\Repository\WishRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use \Symfony\Component\Validator\Constraints as Assert;
#[ORM\Entity(repositoryClass: WishRepository::class)]
#[UniqueEntity(['title'])]
#[ORM\HasLifecycleCallbacks]
class Wish
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 250)]
    #[Assert\NotBlank(message:"Your wish must have a title")]
    #[Assert\Length(min: 1, max: 250, minMessage: "The title must be at least one character long", maxMessage: "The title cannot be more than 250 characters long")]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(options: ['default'=>false])]
    private ?bool $isPublished = false;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateCreated = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateUpdated = null;

    #[ORM\ManyToOne(inversedBy: 'wishes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'wishes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $author = null;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'wish', orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setPublished(bool $isPublished): static
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->dateCreated;
    }

    public function setDateCreated(?\DateTimeInterface $dateCreated): static
    {
        $this->dateCreated = $dateCreated;

        return $this;
    }

    public function getDateUpdated(): ?\DateTimeInterface
    {
        return $this->dateUpdated;
    }

    public function setDateUpdated(?\DateTimeInterface $dateUpdated): static
    {
        $this->dateUpdated = $dateUpdated;

        return $this;
    }

    #[ORM\PrePersist]
    public function beforeSave(){
        $this->setDateCreated(new \DateTime('now'));
        $this->setDateUpdated(new \DateTime('now'));
    }

    #[ORM\PrePersist]
    public function beforeUpdate(){
        $this->setDateUpdated(new \DateTime('now'));
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(?string $author): static
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setWish($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getWish() === $this) {
                $comment->setWish(null);
            }
        }

        return $this;
    }
}

src/Form/WishType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Wish;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WishType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description',null, ['required'=>false])
            ->add('category', EntityType::class, ['required'=>true, 'class'=>Category::class, 'choice_label'=>'name'])
            ->add("addWish", SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Wish::class,
        ]);
    }
}

src/Controller/WishController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Wish;
use App\Form\WishType;
use App\Repository\WishRepository;
use App\Service\Censurator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
USE \Symfony\Component\HttpFoundation\RedirectResponse;
#[Route('/wish')]

class WishController extends AbstractController
{
    #[Route('/list', name: 'wish_list', methods: ['GET'])]
    #[Route('/list', name: 'app_home', methods: ['GET'])]
    public function list(WishRepository $wishRepo): Response
    {
        $wishes = $wishRepo->findAll();
        return $this->render('wish/list.html.twig', ["wishes"=>$wishes]);
    }
    #[Route('/detail/{id}', name: 'wish_detail', requirements: ['id'=>'\d+'], methods: ['GET'])]
    public function detail(Wish $wish): Response
    {
        dump($wish);
        return $this->render('wish/detail.html.twig', ["wish"=>$wish]);
    }

    #[Route('/add', name:'wish_add', methods:['GET', 'POST'])]
public function add(Request $request, EntityManagerInterface $entityManager, Censurator $censurator): Response
    {
        $wish = new Wish();
        $wishForm = $this->createForm(WishType::class, $wish);
        $wishForm->handleRequest($request);

        if($wishForm->isSubmitted() && $wishForm->isValid()){
            $wish->setUser($this->getUser());
            $wish->setDescription($censurator->purify($wish->getDescription()));

            $entityManager->persist($wish);
            $entityManager->flush();

            $this->addFlash('success', 'Idea successfully added');
            return $this->redirectToRoute("wish_detail", ['id'=>$wish->getId()]);
        }

        return $this->render("wish/add.html.twig", ["wishForm"=>$wishForm]);
    }

    #[Route("/update/{id}", name:"wish_update", methods: ['GET', 'POST'])]
    public function update(EntityManagerInterface $entityManager, Request $request, Wish $wish, Censurator $censurator): Response
    {
        $wishForm = $this->createForm(WishType::class, $wish);
        $wishForm->handleRequest($request);

        if($wishForm->isSubmitted() && $wishForm->isValid()){
            $wish->setDescription($censurator->purify($wish->getDescription()));
             $entityManager->persist($wish);
             $entityManager->flush();
             $this->addFlash("success", "Idea edited successfully");
             return $this->redirectToRoute("wish_detail", ["id"=>$wish->getId()]);
        }

        return $this->render("wish/update.html.twig", ['wishForm'=>$wishForm]);
    }

    #[Route("/delete/{id}", name:"wish_delete", methods: ['get'])]
    public function delete(Wish $wish, EntityManagerInterface $entityManager): RedirectResponse
    {
        $entityManager->remove($wish);
        $entityManager->flush();
        $this->addFlash("success", "Idea successfully deleted forever");
        return $this->redirectToRoute("home");
    }

}

templates/wish/add.html.twig
{% extends 'base.html.twig' %}

{% form_theme wishForm 'views/form_theme.html.twig' %}

{% block body %}
    {{ form(wishForm) }}
{% endblock %}

templates/wish/detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="card">
        <h1>detail du souhait</h1>
        <div>title: {{ wish.title }}</div>
        <div>description: {{ wish.description }}</div>
        <div>author: {{ wish.user.username }}</div>
        <div>category: {{ wish.category.name }}</div>
        <div>isPublished: {{ wish.published }}</div>
        <div>createdAt: {{ wish.dateCreated | date('Y/m/d H:i:s') }}</div>
        <div>updatedAt: {{ wish.dateUpdated | date('Y/m/d H:i:s')}}</div>

        <div>Comments:</div>
        {% for comment in wish.comments %}
            <div class="card">
                <div class="flex-row">
                    <div>Created by {{ comment.user.username }} on {{ comment.dateCreated | date('Y-m-d H:i:s') }}</div>
                    {% if app.user.email == comment.user.email %}
                        <a href="{{ path('comment_edit', {id:comment.id}) }}">
                            <button class="small-btn">Modify</button>
                        </a>
                    {% endif %}

                    {% if (app.user.email == comment.user.email or is_granted('ROLE_ADMIN')) %}
                        <a href="{{ path('comment_delete', {id:comment.id}) }}">
                            <button class="small-btn">Delete</button>
                        </a>
                    {% endif %}
                </div>
                <div>{{ comment.content }}</div>
                <div class="flex-row">
                    {% for i in 1..5  %}
                        {% if i <= comment.note %}
                            <div style="width:30px; height:30px">
                                <svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="30px" height="30px" viewBox="0 0 122.88 116.864" enable-background="new 0 0 122.88 116.864" xml:space="preserve"><g><polygon fill-rule="evenodd" clip-rule="evenodd" points="61.44,0 78.351,41.326 122.88,44.638 88.803,73.491 99.412,116.864 61.44,93.371 23.468,116.864 34.078,73.491 0,44.638 44.529,41.326 61.44,0"/></g></svg>
                            </div>
                        {% else %}
                            <div style="width:30px; height: 30px">
                                <svg xmlns="http://www.w3.org/2000/svg" shape-rendering="geometricPrecision" text-rendering="geometricPrecision" image-rendering="optimizeQuality" fill-rule="evenodd" clip-rule="evenodd" viewBox="0 0 512 488.282"><path fill="#fff" fill-rule="nonzero" d="M268.313 8.2l65.464 153.293 166.054 14.902c7.332.632 12.754 7.085 12.118 14.412a13.262 13.262 0 01-4.495 8.87v.006L381.835 309.374l37.159 162.59c1.646 7.181-2.848 14.336-10.03 15.981a13.308 13.308 0 01-10.273-1.84l-142.686-85.309-143.144 85.579c-6.312 3.777-14.492 1.716-18.274-4.602a13.278 13.278 0 01-1.554-9.809l-.016-.006 37.164-162.589L4.551 199.683c-5.536-4.845-6.103-13.263-1.252-18.804a13.281 13.281 0 019.313-4.527l165.611-14.859L243.73 8.119c2.887-6.777 10.722-9.933 17.493-7.052a13.31 13.31 0 017.09 7.133z"/></svg>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endfor %}

            <div class="flex">
                {% if app.user.email == wish.user.email %}
                    <a href="{{ path("wish_update", {id:wish.id}) }}"><button>update</button></a>
                {% endif %}

                {% if (app.user.email == wish.user.email or is_granted('ROLE_ADMIN')) %}
                    <a href="{{ path("wish_delete", {id:wish.id}) }}"><button>delete</button></a>
                {% endif %}

                <a href="{{ path('comment_add', {wishId:wish.id}) }}"><button>Add a comment</button></a>
            </div>
    </div>

{% endblock %}

templates/wish/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class='invert'>Liste des choses souhaits</h1>
    <ul style="overflow-y: scroll;max-height: 70vh">
    {% for wish in wishes %}
        <li class="invert">
            <a href="{{ path("wish_detail", {id:wish.id}) }}">{{ wish.title }} ({{ wish.category.name }})</a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/wish/update.html.twig
{% extends 'base.html.twig' %}

{% form_theme wishForm 'views/form_theme.html.twig' %}

{% block body %}
    <h1>Update your wish</h1>
    {{ form(wishForm) }}
{% endblock %}